version: 2
stages:
  build:
    docker:
      - image: msvrtan/square:0.2.0
    workDir: /var/www
    steps:
      - checkout

      - restore_cache:
          key: cache-{{ checksum "composer.lock" }}

      - run:
          name: Composer install
          command: composer install --no-interaction

      - save_cache:
          key: cache-{{ checksum "composer.lock" }}
          paths:
            - /var/www/vendor
            - /var/www/bin

      - run:
          name: Disable xdebug
          command: ./etc/circleci2/disable-xdebug.sh

      - run:
          name: PHPUnit
          command: ./bin/phpunit

      - run:
          name: PHPSpec
          command: ./bin/phpspec run --no-interaction

      - run:
          name: Check codestandards
          command: ./bin/phing check-codestandards

      - run:
          name: Static analysis
          command: ./bin/phing phpstan

      - run:
          name: Enable xdebug
          command: ./etc/circleci2/enable-xdebug.sh

      - run:
          name: Humbug
          command: ./bin/humbug

      - store_artifacts:
          path: build
          destination: build
