version: 2
stages:
  build:
    docker:
      - image: msvrtan/square:0.2.0
    workDir: /var/www
    steps:
      - checkout

      - restore_cache:
          key: cache-{{ checksum "composer.lock" }}

      - run:
          name: Composer install
          command: composer install --no-interaction

      - save_cache:
          key: cache-{{ checksum "composer.lock" }}
          paths:
            - /var/www/vendor
            - /var/www/bin

      - run:
          name: Disable xdebug
          command: ./etc/circleci2/disable-xdebug.sh

      - run:
          name: PHPUnit
          command: ./bin/phpunit
      - run:
          name: PHPSpec
          command: ./bin/phpspec run --no-interaction

      - run:
          name: Check codestandards
          command: ./bin/phing check-codestandards
      - run:
          name: Static analysis
          command: ./bin/phing phpstan

      - store_artifacts:
          path: build
          destination: build

  humbug:
    docker:
      - image: msvrtan/square:0.2.0
    workDir: /var/www
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "composer.lock" }}
      - run:
          name: Humbug
          command: ./bin/humbug
      - store_artifacts:
          path: build
          destination: build

  lowest:
    docker:
      - image: msvrtan/square:0.2.0
    workDir: /var/www
    steps:
      - checkout
      - restore_cache:
          key: cache-lowest-{{ checksum "composer.lock" }}
      - run:
          name: Disable xdebug
          command: ./etc/circleci2/disable-xdebug.sh
      - run:
          name: Composer install
          command: composer update --prefer-lowest
      - save_cache:
          key: cache-lowest-{{ checksum "composer.lock" }}
          paths:
            - /var/www/vendor
            - /var/www/bin
      - run:
          name: PHPUnit
          command: ./bin/phpunit
      - run:
          name: PHPSpec
          command: ./bin/phpspec run --no-interaction
      - run:
          name: Check codestandards
          command: ./bin/phing check-codestandards
      - run:
          name: Static analysis
          command: ./bin/phing phpstan

  highest:
    docker:
      - image: msvrtan/square:0.2.0
    workDir: /var/www
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "composer.lock" }}
      - run:
          name: Disable xdebug
          command: ./etc/circleci2/disable-xdebug.sh
      - run:
          name: Delete composer.lock
          command: rm composer.lock
      - run:
          name: Composer install
          command: composer install --no-interaction

      - run:
          name: PHPUnit
          command: ./bin/phpunit
      - run:
          name: PHPSpec
          command: ./bin/phpspec run --no-interaction

      - run:
          name: Check codestandards
          command: ./bin/phing check-codestandards
      - run:
          name: Static analysis
          command: ./bin/phing phpstan

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - humbug:
         requires:
           - build
      - highest:
         requires:
           - build
      - lowest:
         requires:
           - build