<?php

declare(strict_types=1);

namespace tests\Devboard\GitHub\Webhook\Core\EventFactory;

use Devboard\GitHub\Webhook\Core\EventFactory\CreateEventFactory;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-25 at 11:40:57.
 */
class CreateEventFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CreateEventFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CreateEventFactory();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
