<?php

declare(strict_types=1);

namespace tests\Devboard\GitHub\Webhook\Core\EventFactory;

use Devboard\GitHub\Webhook\Core\Event\InstallationRepositoriesEvent;
use Devboard\GitHub\Webhook\Core\EventFactory\InstallationEvent\InstallationAccountFactory;
use Devboard\GitHub\Webhook\Core\EventFactory\InstallationEvent\InstallationFactory;
use Devboard\GitHub\Webhook\Core\EventFactory\InstallationRepositoriesEventFactory;
use Devboard\GitHub\Webhook\Core\EventFactory\SenderFactory;
use Generator;
use tests\Devboard\GitHub\Webhook\Core\GitHubExampleTestData;
use tests\Devboard\GitHub\Webhook\Core\GitHubProductionTestData;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-25 at 11:40:57.
 */
class InstallationRepositoriesEventFactoryTest extends \PHPUnit_Framework_TestCase
{
    /** @dataProvider provideArguments */
    public function testCreating(array $data)
    {
        $sut = new InstallationRepositoriesEventFactory(
            new InstallationFactory(
                new InstallationAccountFactory()
            ),
            new SenderFactory()
        );

        $this->assertInstanceOf(InstallationRepositoriesEvent::class, $sut->create($data));
    }

    public function provideArguments(): Generator
    {
        foreach (GitHubProductionTestData::create()->getGitHubInstalationRepositoriesEventData() as $item) {
            yield [$item];
        }

        /*
        // Example from GitHub documentation is outdated and missing data. Dont use it until it gets updated :(
        foreach (GitHubExampleTestData::create()->getGitHubInstalationRepositoriesEventData() as $item) {
            yield [$item];
        }
        */
    }
}
