<?php

declare(strict_types=1);

namespace tests\Devboard\GitHub\Webhook\Core\Event;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-25 at 20:06:58.
 */
class InstallationRepositoriesEventTest extends \PHPUnit_Framework_TestCase
{
    public function testSomething()
    {
    }
}
